---
# title: "Contents"
---



The workshop is structured as follows:

(@) Introduction
(@) Setup coding environment
    + setup Python 
    + setup VSCode 
    + install Github Copilot
(@) Verify OpenAI installation
(@) Using the OpenAI API
(@) Project: Use GPT-4o to generate Anki flashcards
(@) Conclusions and discussion


> 13:30 – 13:45  BegrüssungInput zu Notebook LM (Nina 15’) 
> 
> 13:45 – 14:35  Input: KI erste Schritte, Datenschutz (Andrew 50’) 
> 
> 14:35 – 14:55 Austausch in Gruppen, visuell auf Flipchart (Dana 20’) 1. Wo könnte mir KI helfen, wenn es zaubern könnte 2. Was habe ich für konkrete Aufgaben, die KI für mich lösen dürfte 
> 
> 14:55 – 15:05 >> Gruppen stellen Ergebnisse vor (alle 10’) 
> 
> 14:05 – 15:20 Pause (15’) 
> 
> 15:20 – 15:35 Input Prompting (Andrew 15’) 
> 
> 15:35 – 16:35 (Raymond 60’ total) Einführung zu Tools: Chat GPT, Copilot >> Aufgaben aus Austausch mit Hilfe von Chat GPT / Copilot lösen im Think - Pair – Share (Raymond, Andrew) 
> 
> 16:35 – 16:50 Präsentation der Ergebnisse (15’) 
> 
> 16:50 – 17:00 Austausch, Abschluss (10’) 
> 
> Ab 17:00 Apero mit VMAD-HKB im OG



<!-- 
# Introduction and setup

{{< bi alarm >}} 5 minutes

## Verify Openai 

{{< embed ../notebooks/verify-openai.ipynb#get-ai-response echo=true >}}

{{< embed ../notebooks/verify-openai.ipynb#get-ai-response-2 echo=true >}}


## Test structured output

{{< embed ../notebooks/test-structured-output.ipynb#events echo=true >}}

{{< embed ../notebooks/test-structured-output.ipynb#export-csv echo=true >}}
 -->


<!-- ## Pyodide -->
<!-- 
```{pyodide-python}
n = 5
while n > 0:
  print(n)
  n = n - 1

print('Blastoff!')
``` -->


<!-- # References -->
